require("angel")
.sh()
    .send("git pull")
    .send("git push")
.exit()
.ssh()
    .send("cd ~/project")
    .send("git pull")
    .send("cd ~/project/site")
    .send(". ~/.nvm/nvm.sh; nvm use v0.4.11")
    .send("npm install -d")
    .send("forever stop server.js")
    .send("forever start -o server-output.log -e server-error.log server.js")
.exit()
.export(module)
